// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectController(arg1, arg2) {
  return window['go']['main']['App']['ConnectController'](arg1, arg2);
}

export function CreateButton(arg1) {
  return window['go']['main']['App']['CreateButton'](arg1);
}

export function CreateConfiguration(arg1) {
  return window['go']['main']['App']['CreateConfiguration'](arg1);
}

export function DeleteButton(arg1) {
  return window['go']['main']['App']['DeleteButton'](arg1);
}

export function DeleteConfiguration(arg1) {
  return window['go']['main']['App']['DeleteConfiguration'](arg1);
}

export function DisconnectController(arg1) {
  return window['go']['main']['App']['DisconnectController'](arg1);
}

export function ExecuteAction(arg1) {
  return window['go']['main']['App']['ExecuteAction'](arg1);
}

export function GetAllActionTypes() {
  return window['go']['main']['App']['GetAllActionTypes']();
}

export function GetButton(arg1) {
  return window['go']['main']['App']['GetButton'](arg1);
}

export function GetButtons() {
  return window['go']['main']['App']['GetButtons']();
}

export function GetConfiguration(arg1) {
  return window['go']['main']['App']['GetConfiguration'](arg1);
}

export function GetConfigurationButtonIndicators(arg1) {
  return window['go']['main']['App']['GetConfigurationButtonIndicators'](arg1);
}

export function GetConfigurations() {
  return window['go']['main']['App']['GetConfigurations']();
}

export function GetControllerConfig(arg1) {
  return window['go']['main']['App']['GetControllerConfig'](arg1);
}

export function GetControllerConfigSchema(arg1) {
  return window['go']['main']['App']['GetControllerConfigSchema'](arg1);
}

export function GetControllerStatus(arg1) {
  return window['go']['main']['App']['GetControllerStatus'](arg1);
}

export function GetControllers() {
  return window['go']['main']['App']['GetControllers']();
}

export function GetDefaultConfiguration() {
  return window['go']['main']['App']['GetDefaultConfiguration']();
}

export function GetInputs() {
  return window['go']['main']['App']['GetInputs']();
}

export function GetInstalledPlugins() {
  return window['go']['main']['App']['GetInstalledPlugins']();
}

export function GetOBSStatus() {
  return window['go']['main']['App']['GetOBSStatus']();
}

export function GetScenes() {
  return window['go']['main']['App']['GetScenes']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSourceVisibility(arg1, arg2) {
  return window['go']['main']['App']['GetSourceVisibility'](arg1, arg2);
}

export function InstallPlugin(arg1) {
  return window['go']['main']['App']['InstallPlugin'](arg1);
}

export function ResolveConfiguration(arg1) {
  return window['go']['main']['App']['ResolveConfiguration'](arg1);
}

export function SetDefaultConfiguration(arg1) {
  return window['go']['main']['App']['SetDefaultConfiguration'](arg1);
}

export function TestBinding(arg1) {
  return window['go']['main']['App']['TestBinding'](arg1);
}

export function TestConfiguration(arg1) {
  return window['go']['main']['App']['TestConfiguration'](arg1);
}

export function UninstallPlugin(arg1) {
  return window['go']['main']['App']['UninstallPlugin'](arg1);
}

export function UpdateButton(arg1) {
  return window['go']['main']['App']['UpdateButton'](arg1);
}

export function UpdateClientConfig(arg1, arg2) {
  return window['go']['main']['App']['UpdateClientConfig'](arg1, arg2);
}

export function UpdateConfiguration(arg1) {
  return window['go']['main']['App']['UpdateConfiguration'](arg1);
}
